Task 2 fix
GlazProject/Robots pull request #3
Opened 2023-03-22 13:49 UTC by GlazProject

2023-03-23 03:17 UTC, zzemlyanaya requested changes

2023-03-23 03:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/core/view/ClosingView.java
> +        mainFrame.setIgnoreRepaint(true);
Вот это лучше в GameView обратно вынести, потому что это логика диалога, а остановка repaint относится к логике view

2023-03-23 03:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/core/view/ClosingView.java
> +public class ClosingView {
Я имела в виду что-то вроде DialogFactory ) И методы `showCloseDialog`, `showErrorDialog`, потому что ну при чём здесь логика и view вообще

2023-03-23 03:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/view/GameView.java
> +        if (occurredFatalError) return;
А ты когда ставишь флаг stopRepaint он не перестаёт просто вызывать метод ?

2023-03-23 03:17 UTC, zzemlyanaya commented on src/main/resources/icons.properties
> +target = src/main/resources/sprites/Target/heart.png
он вроде про assets говорил — это общепринятое в gamedev'е

2023-03-23 03:43 UTC, GlazProject commented on src/main/resources/icons.properties
> +target = src/main/resources/sprites/Target/heart.png
Именно это слово я и пытался вспомнить. Хорошо, исправлю

2023-03-23 03:45 UTC, GlazProject commented on src/main/java/ru/projectrobots/game/view/GameView.java
> +        if (occurredFatalError) return;
Он перестаёт отрисовывать gameFrame, а gameView продолжает спамить ошибки

2023-03-24 01:43 UTC, zzemlyanaya approved these changes

2023-03-24 03:08 UTC, merged