[task 4] fix moving & add entity look select
GlazProject/Robots pull request #5
Opened 2023-04-09 16:38 UTC by GlazProject

2023-04-10 03:45 UTC, zzemlyanaya requested changes

2023-04-10 03:45 UTC, zzemlyanaya commented on screenshots.md
> +# ������� �������� ��������
А в какой это кодировке ?... В гите отображается тарабарщина вместо текста )

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/resources/ResourceProvider.java
> +        double scale = 1.0 * height / image.getHeight(null);
Это чтобы сохранять исходное соотношение ?

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/view/panel/MainActionsPanel.java
> +        JButton fireballBtn = new JButton("Огнешар");
Раз несколько шаров сразу генерируем, может в Метеоритный дождь переименовать ?)

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/di/container/GlobalSettings.java
> +    public static void setSprite(String objectId, String name){
А тут с многопоточкой проблем не возникает ?) Мы ведь из разных окон напрямую вызываем методы set

Я бы сказала, что нужно либо volatile вешать, либо делать как с Bus, то есть отправлять запрос на изменение, а сам GlobalSettings уже будет обрабатывать

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/model/Models.java
> +public enum Models {
Элементы enum капсом пишут, в java как минимум

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/model/Models.java
> +public enum Models {
Тут логика в том, что они же константы по сути, а константы капсом

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/model/drawer/FireballDrawer.java
> +                Models.fireball.name() + "." + asset + "." + action + "." + nextFrame,
Судя по всему повторяющийся код, вынеси в функцию 
\+ лучше использовать "%s %s" ака форматированные строки, а не сложение, они эффективнее

2023-04-10 03:45 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/view/panel/MainGameSettingsPanel.java
> +public class MainGameSettingsPanel extends JPanel {
Получается, у внутренних панелей actionFrame нет своих viewModel, да?
С точки зрения архитектуры не очень хорошо — панель не должна заниматься ничем, кроме отрисовки ui
Если в панели только навигация на следующую панель, можно оставить, но где начинается установка GlobalSettings лучше вынести в viewModel эту логику

2023-04-10 03:55 UTC, GlazProject commented on src/main/java/ru/projectrobots/resources/ResourceProvider.java
> +        double scale = 1.0 * height / image.getHeight(null);
Да. Там по ширине места хватает, а вот по высоте нужно выравнивать

2023-04-10 03:56 UTC, GlazProject commented on src/main/java/ru/projectrobots/game/view/panel/MainActionsPanel.java
> +        JButton fireballBtn = new JButton("Огнешар");
Почему несколько? Кнопка по прежнему запускает только один шар. Но можно добавить ещё одну, которая просто 10 событий посылает

2023-04-10 05:46 UTC, GlazProject commented on src/main/java/ru/projectrobots/game/view/panel/MainGameSettingsPanel.java
> +public class MainGameSettingsPanel extends JPanel {
Панели реализуют только переход в другую вкладку меню, вся логика работы находится в `ActionFrameViewModel.java`

2023-04-10 05:46 UTC, GlazProject commented on src/main/java/ru/projectrobots/di/container/GlobalSettings.java
> +    public static void setSprite(String objectId, String name){
Готово )

2023-04-10 14:17 UTC, zzemlyanaya requested changes

2023-04-10 14:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/model/drawer/FireballDrawer.java
> +                Models.FIREBALL + "." + asset + "." + action + "." + nextFrame,
А зачем тебе createFullName, если ты его не используешь ?)

2023-04-10 14:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/viewmodel/ActionFrameViewModel.java
> +                eventBus.sendData(new GameEvent<>(
```
 eventBus.sendData(new GameEvent**<LookEntry>**(
                        GameEventType.UPDATE_LOOK,
                        new LookEntry(data[1], data[2])));
```
И тогда ниже (я поставлю \+) передавать не Object

2023-04-10 14:17 UTC, zzemlyanaya commented on src/main/java/ru/projectrobots/game/viewmodel/GameViewModel.java
> +    private void updateGlobalSettings(Object entry){
\+

2023-04-10 18:00 UTC, GlazProject commented on src/main/java/ru/projectrobots/game/model/drawer/FireballDrawer.java
> +                Models.FIREBALL + "." + asset + "." + action + "." + nextFrame,
Ну ведь в RobotDrawer исправил )
Совсем забыл про это, исправлю

2023-04-10 18:03 UTC, GlazProject commented on src/main/java/ru/projectrobots/game/viewmodel/GameViewModel.java
> +    private void updateGlobalSettings(Object entry){
Согласен, посмотрю, как это аккуратнее сделать. Там с Genetic может не очень получаться

2023-04-11 04:27 UTC, zzemlyanaya approved these changes

2023-04-14 09:23 UTC, zzemlyanaya approved these changes

2023-04-18 05:53 UTC, merged